### ISSUE TITLE
COMPARE_SurfaceLabelCleanUp failing on Medusa

### ISSUE THREAD

**Issue by dmwelch** [BRAINSia/BRAINSTools#165]
Test failing since Nov. 19th: http://testing.psychiatry.uiowa.edu/CDash/viewTest.php?onlyfailed&buildid=37787

Broken revision link: https://github.com/BRAINSia/BRAINSTools/commits/e13105f37b55d66cf1b7be22dea9caca08ce51b9..adb3a2ef5bbb20cebfa8d4c7f5fa569b1a65f9b4

**Comment by hjmjohnson** [comment]
@dgellis90 David  Are you making progress on this issue?

**Comment by dgellis90** [comment]
The test is failing during the comparison because the scalar values of 0th component at 0th tuple in 0th array are different between the two surfaces. So either the reference surface is incorrect, or the SurfaceLabelCleanUp code is not doing what it's supposed to. However, it is not giving any errors or failing, so I'm not really sure where to start looking in the SurfaceLabelCleanUp code. It does output a surface, but I'm not sure how to manually check if it is the correct surface.

**Comment by dgellis90** [comment]
Pull request #173 should fix this issue.

**Comment by hjmjohnson** [comment]
Pull request #173 should fix this issue.
