### ISSUE TITLE
DWIConvert FSLToNrrd fails on a DRBUDDI dwi

### ISSUE THREAD

**Issue by reckbo** [BRAINSia/BRAINSTools#343]
git clone https://github.com/pnlbwh/BRAINSTools-debug && cd BRAINSTools-debug
    make dwibuddi10.nrrd

Load `dwibuddi10.nrrd` in Slicer and you'll see the slices are garbled.

**Comment by ihnorton** [comment]
I took a quick look, and believe that the issue is casting from float to short:
![image](https://cloud.githubusercontent.com/assets/327706/24815280/9c84e052-1ba2-11e7-85f6-ae34b68c3f56.png)

The nifti1 `datatype` of the linked data is float32, but the readers are *only* instantiated for short (that's why I added the error about lossy conversion -- which no longer seems to be thrown...).

I'll have to punt on this for the moment. A possible work-around would be to do a cast back down to short.

@reckbo btw, where did you get this dataset? Seems like a useful (small, multi-bval) test set if the licensing is amenable. I googled around and found some DR-BUDDI pages but didn't manage to find this data. (assuming the MR scanner is not acquiring in float, I would suspect this data ended up as float somewhere in the pipeline because of the scl_slope field, which has a long history of causing confusion in both ITK and the Nifti world in general)

**Comment by reckbo** [comment]
@ihnorton Sorry for the long time in responding, I was away for a while.  I'm revisiting this issue now and will report back with what I find out.

**Comment by hjmjohnson** [comment]
@reckbo Any progress on this? Can this issue be closed?

**Comment by reckbo** [comment]
@hjmjohnson  Yes I'm going to close this issue, from what I've gathered DR-BUDDI generates a nifti that has non-standard semantics, so we can't expect DWIConvert to work correctly.

**Comment by hjmjohnson** [comment]
Thank you.
