### ISSUE TITLE
DWIConvert: Nrrd -> FSL -> Nrrd != Nrrd

### ISSUE THREAD

**Issue by reckbo** [BRAINSia/BRAINSTools#350]
Using the most recent commit as well as 3 others, I find that this transformation changes 'space thicknesses' and the last axis of 'space origin' of a given nrrd DWI.

I've attached a summary:

[DWIConvertTest.pdf](https://github.com/BRAINSia/BRAINSTools/files/1206623/DWIConvertTest.pdf)

(`dwinrrd` is the original nrrd and `dwifslnrrd` is the one generated via nrrd->fsl->nrrd)

**Comment by hjmjohnson** [comment]
[DWIVisualizationFixing.pptx](https://github.com/BRAINSia/BRAINSTools/files/1206727/DWIVisualizationFixing.pptx)

@reckbo  We did a lot of testing last year to ensure that the results were consistent across several data types for FSL and NRRD.  https://github.com/BRAINSia/BRAINSTools/tree/master/DWIConvert/TestSuite

I can't claim that all the bugs are gone, but we did identify several results that were wrong.

We did the nrrd->fsl->nrrd conversions as well.  It is not possible to retain some orientation informations through that conversion process because fsl format is not as flexible as nrrd.

**Comment by hjmjohnson** [comment]
@Hui-Xie 

Hui,  Please monitor this thread to ensure that DWIConvert is working reliably for new data types.

Hans

**Comment by hjmjohnson** [comment]
I think that this issue was addressed in a previous message.  

We did the nrrd->fsl->nrrd conversions as well. It is not possible to retain some orientation informations through that conversion process because fsl format is not as flexible as nrrd.
